# Generated by Django 2.2.4 on 2019-09-14 09:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mtaa', '0002_auto_20190914_1144'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='email',
        ),
    ]
