# Generated by Django 2.2.4 on 2019-09-14 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mtaa', '0002_auto_20190914_1606'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='phone',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='neighbourhood',
            name='occupants_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='phone',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=10),
        ),
    ]
